file:
  dir: C:/Users/begywjd/file/

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/file-attach;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  messages:
    basename: messages,error

logging.level:
  org.hibernate.SQL: debug